version: '2.1'
services:
  db:
    network_mode: 'bridge'
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=Insertedd
      - MYSQL_DATABASE=blogs
    expose:
      - 3306
    ports:
      - '3308:3306'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3306/blogs']
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

  client:
    build: ./client
    network_mode: 'bridge'
    restart: 'on-failure'
    stdin_open: true
    tty: true
    container_name: next_app
    depends_on:
      - db
    expose:
      - 3000
    ports:
      - '3000:3000'
    volumes:
      - '/home/icepops/shared/tinyblogs:/app'
